apiVersion: v1
kind: Service
metadata:
  name: my-simple-app-service
spec:
  type: NodePort
  selector:
    app: my-simple-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007  # Minikube will expose this on <minikube-ip>:30007

