pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/yogitha-koya/Devops-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r Task2/requirements.txt'
            }
        }

        stage('Run Application') {
            steps {
                sh 'python Task2/main.py'
            }
        }

        stage('Test') {
            steps {
                sh 'pytest Task2/test_main.py'
            }
        }
    }

    post {
        success {
            echo '✅ Build and tests successful!'
        }
        failure {
            echo '❌ Build or tests failed!'
        }
    }
}

