pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
        PROJECT_DIR = 'Task2'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/yogitha-koya/Devops-project.git', branch: 'main'
            }
        }

        stage('Set Up Virtualenv') {
            steps {
                sh '''
                    python3 -m venv ${VENV_DIR}
                    bash -c "source ${VENV_DIR}/bin/activate && pip3 install --upgrade pip"
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    bash -c "source ${VENV_DIR}/bin/activate && pip3 install -r ${PROJECT_DIR}/requirements.txt"
                '''
            }
        }

        stage('Run App') {
            steps {
                sh '''
                    bash -c "source ${VENV_DIR}/bin/activate && python3 ${PROJECT_DIR}/main.py"
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    bash -c "source ${VENV_DIR}/bin/activate && pytest ${PROJECT_DIR}/test_main.py"
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
        always {
            echo '🧹 Cleaning up...'
            sh "rm -rf ${VENV_DIR}"
        }
    }
}
