@Library("my-shared-library") _
pipeline {
    agent { label 'agent1' }

    stages {
        stage('Hello') {
            steps {
                helloWorld()
            }
        }
        stage('Build') {
            steps {
                buildMaven()
            }
        }
    }
}
